name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositpry
        uses: actions/checkout@v5

      - name: run a one-line script
        run: eche Hello World!
